# **Pytorch Fundamentals**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors  

A vector is a measure of magnitude in a given direction, represented as an array of numbers like (x, y, z).  
If a vector is a 1D array, a matrix is a 2D array, then a tensor is basically a multidimensional array.
Tensors are very good for computation in deep learning as they allow for fast processing.  
All arrays have a tensor rank. The tensor rank is given by the amount of dimensions (Rank 1 = Vector, Rank 2 = Matrix, etc...)  
  
In Pytorch, all types of these arrays are still of a "tensor" data type.

### Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Pytorch tensors are creating using

```
torch.tensor()
```

Pytorch Documentation Definition:  
A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

In [ ]:
scalar.ndim # checking the number of dimensions

0

In [ ]:
scalar.item() # changes it back to a regular python integer

7

In [ ]:
# Vector - 1D Array
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim # 1 dimension (# of square brackets)

1

In [ ]:
vector.shape # shape of the array (2 by 1 elements)

torch.Size([2])

In [ ]:
# MATRIX - 2D Array
MATRIX = torch.tensor([[7, 8],
                       [9, 8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [ ]:
MATRIX.ndim # 2 Square brackets:

2

In [ ]:
MATRIX[0, 1] # Indexes like a normal array

tensor(8)

In [ ]:
MATRIX.shape # 2 by 2

torch.Size([2, 2])

In [ ]:
# TENSOR - 3D array
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim # 3 Dimensions

3

In [ ]:
TENSOR.shape # we have one 3 by 3 shaped tensor

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR = torch.tensor([[[[3, 3, 4], [1, 2, 4], [1 , 2, 3]],
                        [[3, 3, 4], [1, 2, 4], [1 , 2, 3]]]])
print( TENSOR.shape )
print( TENSOR.ndim )

torch.Size([1, 2, 3, 3])
4


##### So basically the dimensions start at the blue brackets (since the arry is literally everything incomposed in the pink brackets).  
##### There is one blue bracket so 1 dimension of 2 (two yellow brackets inside the blue brackets) dimensions of 3 (three purple brackets in each yellow bracket) of 3 (3 elements inside each purple bracket).

#### In summary, it is how many elements are in each bracket.

### Random Tensors  
  
Why random tensors?  
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbesr and then adjust those randoms numbers to better represent the data.


`Start w/ random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`



In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3386, 0.2039, 0.4300, 0.4412],
        [0.2629, 0.2799, 0.1775, 0.8895],
        [0.5095, 0.4444, 0.5690, 0.8579]])

In [ ]:
random_tensor.ndim # 2 Dimensions (3 by 4)

2

In [ ]:
# Create a random tensor w/ similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, color changes (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

So images can be represented as tensors (tensors are very similar to numpy arrays, which images basically are)  
  
##### Also the "size=" is an optional part of the size parameter. It can go either way when creating tensors.

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zero = torch.zeros(size=(3, 4))
# Useful for creating masks, as when multiplying tensors by zero, they become zero.
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
one = torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one.dtype # Default datatype is .float

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange(start, end, step)
one_to_nine = torch.arange(1, 10, step=3) # Starts indexing out zero, so this goes 1-9. Stepsize of 3.

In [ ]:
# Creating tensors like
three_zeros = torch.zeros_like(input=one_to_nine) # creates a new tensor with old tensor's shape
three_zeros

tensor([0, 0, 0])

### Tensor Datatypes  
  
**Note:** Tensor datatypes are one of the 3 big errors encountered with Pytorch & deep learning:  
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (float32 is default)
                               device=None, # What device is your tensor on (CPU is default)
                               requires_grad=False) # Whether or not to track gradients w/ this tensors operations

A single-precision floating point is called a float 32.  
Half-precision is called float 16.  
If you want to compute faster but sacrifice detail, you can use float 16. If you need more precision, you might go up to float 64.

In [ ]:
# Converting Datatypes
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)