<h1><center> NumPy Notes </center></h1>

### **Comparing Python lists and NumPy arrays**

#### Here is where they are similar:


In [1]:
# Normal Python lists:

a = [1,2,3,4,5]
print(a)
print(a[1])
print(a[-1])
print(a[1:4])

[1, 2, 3, 4, 5]
2
5
[2, 3, 4]


In [3]:
# NumPy arrays:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
print( type(a) ) #getting the type

# Works like normal Python lists
print(a)
print(a[1])
print(a[1:])
a[2] = 10 # assignment
print(a)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
2
[2 3 4 5]
[ 1  2 10  4  5]


#### Here is where they differ:

In [10]:
import numpy as np

# Dimensional Arrays (list within a list):
a_mul = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(a_mul)

print("Printing 9: ", a_mul[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Printing 9:  9
Get Dimension:  2
Get Size:  9
Get item:  (3, 3)


In [12]:
# Get Dimension:
print(a_mul.ndim)
# Get Shape:
print(a_mul.shape)

2
(3, 3)


In [16]:
# Array Math:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)
print(a**2) # to the 2nd power
print(a/b)

[5 7 9]
[ 4 10 18]
[1 4 9]
[0.25 0.4  0.5 ]


### Accessing/Changing Specific Elements:

**Keep in mind that indexing starts at 0**

In [8]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [28]:
# Get a specific element: [row, column]
a[0,3]

4

In [29]:
# Also do negative indexing:
a[0,-2]

6

In [30]:
# Get a specific row:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column:
a[:, 2]

array([ 3, 10])

In [32]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [36]:
# Changing elements;
a[1,5] = 20 # 13 to 20
print(a)

# Changing a column:
a[:,2] = 0
print(a)

[[ 1  2  0  4  5  6  7]
 [ 8  9  0 11 12 20 14]]
[[ 1  2  0  4  5  6  7]
 [ 8  9  0 11 12 20 14]]


In [4]:
# 3D Example:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (work outside in):
print( b[0,1,1] )
# Get array:
print( b[:,1,:] )

4
[[3 4]
 [7 8]]


In [5]:
# Replace:
b[:,1,:] = [[9,9],[1,7]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [1 7]]]


### Different Types of Arrays:

In [6]:
# All 0s matrix:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# All 1s matrix:
np.ones((2,3,3))

In [7]:
# Any other number:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [10]:
# Any other number (full like):
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

#### **Be careful when copying arrays!**

In [11]:
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


Changes both a and b! Do this instead:

In [12]:
# Use the copy function for duplicating arrays:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Random Generation

In [13]:
np.random.rand(2, 3)         # Uniform [0, 1)
np.random.randn(2, 3)        # Standard normal (mean 0, std 1)
np.random.randint(0, 10, 5)  # 5 random ints from 0–9

None


### Statistics

In [16]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.min(stats, axis=1) # 0 is for column, 1 is row.

array([1, 4])

In [19]:
np.max(stats)

6

In [23]:
np.sum(stats)

21

### Reorganizing Arrays

In [25]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

# Reshaping:
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Common Utilities

In [36]:
a = np.unique((1,8,2,4,2))               # Returns sorted unique values
b = np.sort((1,2,3,2))                 # Sorted array
c = np.concatenate([a, b])       # Join arrays

print(a)
print(b)
print(c)

[1 2 4 8]
[1 2 2 3]
[1 2 4 8 1 2 2 3]
